name: Node-CI Beta

on:
  push:
    branches:
      - beta

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test-coverage
        env:
          CI: true

  publish-npm:
    if: github.repository == 'homebridge/ciao' # publish only if we are on our own repo

    needs: build # only run if build succeeds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: node .github/workflows/prerelease.js
      - run: npm --no-git-tag-version version pre --preid=beta
      - run: npm publish --access public --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
